## Simple Syntax

In [1]:
println("Hello world")

Hello world


In [2]:
my_ans = 42
typeof(my_ans)

Int64

In [3]:
my_pi = 3.14159
typeof(my_pi)

Float64

In [4]:
# This is a single line comment

In [5]:
#=

This is a 
multi-line comment.

=#

In [6]:
s = 3 + 4
d = 10 - 3
p = 20 * 5
q = 100 / 10
po = 10^2
m = 101 % 2
println(s, " ", d, " ", p, " ", q, " ", po, " ", m)
println(typeof(s), " ", typeof(d), " ", typeof(p), " ", typeof(q), " ", typeof(po), " ", typeof(m))

7 7 100 10.0 100 1
Int64 Int64 Int64 Float64 Int64 Int64


In [7]:
days = 365
days_f = convert(Float64, days)

365.0

In [8]:
# This does not work in VSCode notebook, but will work in browser based notebook
?convert

LoadError: syntax: invalid identifier name "?"

In [9]:
convert(Int64, "1")

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Int64
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:273
  ...

In [10]:
@assert days == 365
@assert days_f == 365.0

In [11]:
convert(Int64, "1")

LoadError: MethodError: Cannot `convert` an object of type String to an object of type Int64
Closest candidates are:
  convert(::Type{T}, ::T) where T<:Number at number.jl:6
  convert(::Type{T}, ::Number) where T<:Number at number.jl:7
  convert(::Type{T}, ::Base.TwicePrecision) where T<:Number at twiceprecision.jl:273
  ...

In [12]:
?parse

search: parse tryparse partialsortperm partialsortperm! pairs skipchars



```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```
parse(::Type{Platform}, triplet::AbstractString)
```

Parses a string platform triplet back into a `Platform` object.


In [13]:
parse(Int64, "1")

1

In [14]:
parse(Complex{Float64}, "3.2 + 4.5i")

3.2 + 4.5im

In [15]:
parse(Int64, "FF", base=16)

255

In [16]:
s1 = "This is a string"

s2 = """
This is also a string
that can span multiple lines.
"""

"This is also a string\nthat can span multiple lines.\n"

In [17]:
println(s2)

This is also a string
that can span multiple lines.



In [18]:
c = 'A'  # single quotes are char

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [19]:
typeof(c)

Char

In [20]:
name = "APTG"
n_cookies = 2
n_cakes = 1
println("Hello I am $name and I ate $(n_cookies + n_cakes) treats today!")

Hello I am APTG and I ate 3 treats today!


In [21]:
string("hello my name is ", name, " notice the spaces that I have to add.")

"hello my name is APTG notice the spaces that I have to add."

In [22]:
greeting = "hello my name is "
greeting * name

"hello my name is APTG"

In [23]:
greeting + name

LoadError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:591

In [24]:
repeat(name, 3)

"APTGAPTGAPTG"

In [25]:
name^3

"APTGAPTGAPTG"

In [26]:
a = 3
b = 4
c = "$a + $b"
d = "$(a + b)"
println("c=$c d=$d")

c=3 + 4 d=7


In [27]:
@assert c == "3 + 4"
@assert d == "7"

## Builtin Data Structures

There is some weirdness around using commas, semicolons, and spaces to create vectors and matrices. More details in this [discussion](https://discourse.julialang.org/t/whats-the-meaning-of-the-array-syntax/938).

### Tuple

#### Indexable but immutable

In [28]:
fruits = ("apple", "mango", "banana")
typeof(fruits)

Tuple{String, String, String}

In [29]:
fruits[1]

"apple"

In [30]:
fruits[1] = "pear"

LoadError: MethodError: no method matching setindex!(::Tuple{String, String, String}, ::String, ::Int64)

#### Mixed element types

In [31]:
mix = ("hello", 42)
typeof(mix)

Tuple{String, Int64}

### NamedTuple
Just like tuple but with property names in **addition** to being indexable.

In [32]:
stocks = (FB=335.24, MSFT=334.69, U=145.57)
typeof(stocks)

NamedTuple{(:FB, :MSFT, :U), Tuple{Float64, Float64, Float64}}

In [33]:
stocks[1]

335.24

In [34]:
stocks.FB

335.24

In [35]:
stocks.FB = 440

LoadError: setfield!: immutable struct of type NamedTuple cannot be changed

### Dictionaries

Unlike Python, insertion order is not preserved.

In [36]:
flavors = Dict(
    "Chocolate Chip" => 200,
    "Snicker Doodle" => 220
)

Dict{String, Int64} with 2 entries:
  "Chocolate Chip" => 200
  "Snicker Doodle" => 220

In [37]:
calories = Dict(
    200 => "Chocloate Chip",
    220 => "Snicker Doodle"
)

Dict{Int64, String} with 2 entries:
  200 => "Chocloate Chip"
  220 => "Snicker Doodle"

#### Indexable

In [38]:
flavors["Chocolate Chip"]

200

In [39]:
calories[200]

"Chocloate Chip"

#### Iterators for keys and values

In [40]:
keys(calories)

KeySet for a Dict{Int64, String} with 2 entries. Keys:
  200
  220

In [41]:
values(calories)

ValueIterator for a Dict{Int64, String} with 2 entries. Values:
  "Chocloate Chip"
  "Snicker Doodle"

#### Mutable
Two ways - add a new entry, modify an existing entry.

In [42]:
flavors["Snicker Doodle"] = 240

240

In [43]:
flavors

Dict{String, Int64} with 2 entries:
  "Chocolate Chip" => 200
  "Snicker Doodle" => 240

In [44]:
flavors["Oatmeal Raisin"] = 180

180

In [45]:
flavors

Dict{String, Int64} with 3 entries:
  "Chocolate Chip" => 200
  "Snicker Doodle" => 240
  "Oatmeal Raisin" => 180

#### push! and pop! support
Support for `push!` and `pop!` as with all other mutable containers.

In [46]:
pop!(flavors, "Oatmeal Raisin")

180

In [47]:
flavors

Dict{String, Int64} with 2 entries:
  "Chocolate Chip" => 200
  "Snicker Doodle" => 240

#### Mixed types
Keys and values can be of different types.

In [48]:
mixhsh = Dict("one" => 1, 1 => "ek", 1.0 => "uno")

Dict{Any, Any} with 2 entries:
  "one" => 1
  1.0   => "uno"

#### Check membership
Multiple ways to check if a key is in the dictionary.

In [49]:
haskey(flavors, "Chocolate Chip")

true

In [50]:
"Chocolate Chip" in keys(flavors)

true

In [51]:
# the ∈ is typed by pressing \in followed by a tab.
"Chocolate Chip" ∈ keys(flavors)

true

### Arrays

Key differences from Python -
  * 1 based indexing
  * Negative indexes don't work
  * Slices are inclusive on both sides

In [52]:
nums = [1, 2, 3, 4, 5, 6]

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

In [53]:
nums[1]

1

In [54]:
nums[-1]

LoadError: BoundsError: attempt to access 6-element Vector{Int64} at index [-1]

In [55]:
nums[2:4]

3-element Vector{Int64}:
 2
 3
 4

#### Mutable
Are mutable in the sense that value at existing index can be changed. But a new index cannot be added with the index operator, have to use the `push!` function which pushes a new element at the end of the array. Also, like all other mutable containers, supports the `pop!` function which pops the last element.

In [56]:
nums[1] = 100

100

In [57]:
nums

6-element Vector{Int64}:
 100
   2
   3
   4
   5
   6

In [58]:
nums[7] = 7

LoadError: BoundsError: attempt to access 6-element Vector{Int64} at index [7]

In [59]:
push!(nums, 7)

7-element Vector{Int64}:
 100
   2
   3
   4
   5
   6
   7

In [60]:
pop!(nums)

7

In [61]:
nums

6-element Vector{Int64}:
 100
   2
   3
   4
   5
   6

#### Copying
Using the `=` operator to copy an array is not going to work. It will just create a new reference to the existing underlying array. Use the `copy` function instead which will do a `memcpy`.

In [62]:
colors = ["red", "gree", "blue"]
also_colors = colors
colors[1] = "magenta"
println(colors)
println(also_colors)

["magenta", "gree", "blue"]
["magenta", "gree", "blue"]


In [63]:
colors = ["red", "gree", "blue"]
also_colors = copy(colors)
colors[1] = "magenta"
println(colors)
println(also_colors)

["magenta", "gree", "blue"]
["red", "gree", "blue"]


#### Mixed types
Array (or Vector) elements can be different types.

In [64]:
mixary = [1, 2, "red", 3.14]

4-element Vector{Any}:
 1
 2
  "red"
 3.14

## Loops

In [65]:
n = 0
while n < 10
    n += 1
    println(n)
end
n

1
2
3
4
5
6
7
8
9
10


10

In [66]:
for n in 1:10
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [67]:
m, n = 5, 5
A = fill(0, (m, n))

5×5 Matrix{Int64}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [68]:
for j in 1:n
    for i in 1:m
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [69]:
B = fill(0, (m, n))
for j in 1:n, i in 1:m
    B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [70]:
C = [i + j for i in 1:m, j in 1:n]

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

## Conditionals

In [71]:
n = 11

11

In [72]:
if (n % 3 == 0) && (n % 5 == 0)
    println("FizzBuzz")
elseif n % 3 == 0
    println("Fizz")
elseif n % 5 == 0
    println("Buzz")
else
    println(n)
end

11


In [73]:
x = 10
y = 30
(x > y) ? println("x is greater") : println("y is greater")

y is greater


## Functions
Defined using the `function` and `end` keywords.

In [74]:
function sayhi(name)
    println("Hi $name")
end

sayhi (generic function with 1 method)

In [75]:
sayhi("APTG")

Hi APTG


In [76]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [77]:
y = f(3)
println("Even though there is no explicit return stmt the function returned $y")

Even though there is no explicit return stmt the function returned 9


In [78]:
typeof(f)

typeof(f) (singleton type of function f, subtype of Function)

#### In a single line

In [79]:
altf(x) = x^2
altf(10)

100

#### Lambdas

In [80]:
anon1 = n -> println("Hi $name")
anon2 = x -> x^2

#5 (generic function with 1 method)

In [81]:
tp = anon1("APTG")

Hi APTG


In [82]:
anon2(10)

100

#### Support for duck typing
But only works where there is no ambiguity on what needs to be done. E.g., the power operator is defined for the matrix type, so passing a matrix to `f` will work. This operator is also defined for strings, so passing in a string will work as well. But it is undefined for vectors, so passing in a vector will raise an error.

In [83]:
sayhi(23)

Hi 23


In [84]:
f("hello ")

"hello hello "

In [85]:
f(rand(3, 3))

3×3 Matrix{Float64}:
 0.50063   1.56922  1.17907
 0.442558  1.32505  0.879063
 0.153289  0.54223  0.493324

In [86]:
f(rand(3))

LoadError: MethodError: no method matching ^(::Vector{Float64}, ::Int64)
Closest candidates are:
  ^(::Union{AbstractChar, AbstractString}, ::Integer) at strings/basic.jl:730
  ^(::LinearAlgebra.Symmetric{var"#s886", S} where {var"#s886"<:Real, S<:(AbstractMatrix{<:var"#s886"})}, ::Integer) at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:674
  ^(::LinearAlgebra.Symmetric{var"#s886", S} where {var"#s886"<:Complex, S<:(AbstractMatrix{<:var"#s886"})}, ::Integer) at /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/LinearAlgebra/src/symmetric.jl:675
  ...

#### Functors
I can convert `f` into a Functor simply by using the `.` operator! So now passing in a vector simply does an element-wise squaring. Similarly passing in a matrix will do element-wise squaring instead of doing a full matrix times matrix op. This is called the `broadcast` operator and there is also an eponymous function that does the same thing.

In [87]:
f.([1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [88]:
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [89]:
f.(A)

5×5 Matrix{Int64}:
  4   9  16  25   36
  9  16  25  36   49
 16  25  36  49   64
 25  36  49  64   81
 36  49  64  81  100

#### Naming
Just like in Ruby, mutating functions are suffixed with `!`. See for example `sort()` and `sort!()`.

In [90]:
v = [3, 5, 2]

3-element Vector{Int64}:
 3
 5
 2

In [91]:
u = sort(v)
println(u)
println(v)

[2, 3, 5]
[3, 5, 2]


In [92]:
u = sort!(v)
println(u)
println(v)

[2, 3, 5]
[2, 3, 5]


In [93]:
calories

Dict{Int64, String} with 2 entries:
  200 => "Chocloate Chip"
  220 => "Snicker Doodle"

In [94]:
map(x -> x + 10, calories)

LoadError: map is not defined on dictionaries

In [95]:
map(x -> x + 10, keys(calories))

LoadError: map is not defined on sets

In [96]:
fruits

("apple", "mango", "banana")

In [97]:
map(n -> length(n), fruits)

(5, 5, 6)

In [98]:
map(f, v)

3-element Vector{Int64}:
  4
  9
 25

## Packages

Go to https://julialang.org/packages/ to see all the packages. Two ways to add packages - one is in the REPL press `]` to enter the package mode and then `add` the package name. To get out of the package mode hit the [delete] key.

I can also add packages programmatically -

In [112]:
using Pkg
Pkg.add("Example")

    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.8/Project.toml`
  No Changes to `~/.julia/environments/v1.8/Manifest.toml`


In [113]:
names(Example)

LoadError: UndefVarError: Example not defined

In [114]:
using Example

In [115]:
hello("APTG")

"Hello, APTG"

## User Defined Types
Structs are the way to define new types in Julia. They come with a default constructor which takes in all the fields in the order they were specified in the struct definition.

### Immutable

In [116]:
struct Cookie
    flavor::String
    calories::Int
end

In [117]:
cc = Cookie("Chocolate Chip", 200)

Cookie("Chocolate Chip", 200)

In [118]:
sd = Cookie(flavor="Snicker Doodle", calories=220)

LoadError: MethodError: no method matching Cookie(; flavor="Snicker Doodle", calories=220)
Closest candidates are:
  Cookie(::String, ::Int64) at In[116]:2 got unsupported keyword arguments "flavor", "calories"
  Cookie(::Any, ::Any) at In[116]:2 got unsupported keyword arguments "flavor", "calories"

In [119]:
cc.calories

200

In [120]:
cc.calories = 220

LoadError: setfield!: immutable struct of type Cookie cannot be changed

### Use the `mutable` keyword

In [121]:
mutable struct Cookie2
    flavor::String
    calories::Int
end

In [122]:
sd = Cookie2("Snicker Doodle", 220)

Cookie2("Snicker Doodle", 220)

In [123]:
sd.calories = 240

240

In [124]:
sd

Cookie2("Snicker Doodle", 240)

### Custom CTOR
The `new` keyword actually goes and creates the object. It is like calling the default ctor, so it needs all the fields.

In [125]:
struct Cookie3
    flavor::String
    calories::Int
    count::Int

    function Cookie3(flavor, calories)
        new(flavor, calories, 100)
    end
end

In [126]:
oatr = Cookie3("Oatmeal Raisin", 200)

Cookie3("Oatmeal Raisin", 200, 100)

This is just one way of defining constructors. Read [constructors](https://docs.julialang.org/en/v1/manual/constructors/) for a fuller treatment of this subject.