# Basics

## Printing

In [1]:
println("Hello, Julia Notebook")
print("Hello without newline")
print("This is APTG")

Hello, Julia Notebook
Hello without newlineThis is APTG

## Basic Style Guide

Ref: https://docs.julialang.org/en/v1/manual/style-guide/#Indentation

When in doubt I should refer to the code in [Julia base])(https://github.com/JuliaLang/julia/tree/master/base).

Instead of writing the full style guide here, I am trying something different. I'll only write down the styles related to the parts of the language I am covering in any given notebook. In this notebook I cover the basics of the language, so I'll only mention the style guide needed to write basic code.

  * Use 4 spaces per indentation level.
  * Don't parenthesize conditions or while loops
  ```julia
  if a == b
  ```
  instead of:
  ```julia
  if (a == b)
  ```
  * The official style guide does not have any specific guidelines for variable names so I'll follow the guidelines for function names. Lowercase and when readable, with multiple words squashed together, otherwise use snake case.
  * Avoid using floats for numeric literals in generic code when possible. Not using floats will prevent unecessary type promotions/conversions.

## Documentation

Ref: https://docs.julialang.org/en/v1/manual/documentation/

Julia supports Markdown docstrings by default. Below is an example of how to write docstrings. Somethings to note -
  * There should be no whitespace between the docstring and the function/data type definition.
  * The starting and ending triple quotes should be on their own separate line.
  * The first line should be a simplified signature block. It should be indented at 4 spaces and typically be the Julia object that is being documented.
  * After the simplified signature block, a single one-line sentence describing what the function does or what the object reprsents. The one-line sentence should use the imperative "Do this" or "Return that" instead of third person, e.g., "Returns the". End this line with a period.
  * The examples can be codefenced as `jldoctest` and then I can run automated doctests on the file. I don't know how to do this just yet, but it is good to be in the habit of writing documentation like this.
  * I can also use the `julia-repl` codefence in my examples if I want.
  * Include Latex expressions in double backticks. Use the unicode characters instead of latex, e.g., $\alpha$ instead of `\alpha`. 

In [1]:
"""
    bar(x[, y])

Compute the Bar index between `x` and `y`.

If `y` is unspecified, compute the Bar index between all pairs of columns of `x`.

# Examples
```jldoctest
julia> bar([1, 2], [1, 2])
1
```
"""
function bar(x, y)
    1
end

bar

## Basic Types

Here are some basic types that are good to know to follow this notebook. A detailed discussion on types is in another notebook.

  * Numeric types

```
Number (abstract)
└── Real (abstract)
    ├── AbstractFloat (abstract)
    │   ├── Float16
    │   ├── Float32
    │   ├── ...
    └── Integer (abstract)
        └── Signed (abstract)
            ├── Int8
            ├── Int16
            └── ...
```

  * `Int` is an alias for `Int64` on 64bit systems.

  * String types

```
AbstractString (abstract)
├── String
└── ...
```

Here are a few type-based operators/functions that are useful to know -
  * `typeof(obj)` - gives the concrete type of the given object.
  * `isa(obj, type)` - checks if the given type is an ancestor of the given object.
  * `<:(type, type)` - checks if the given type is an ancestof of the second given type.
  * `supertype(type)` - gives the immediate parent of the given type.

In [13]:
ans = 42

42

In [14]:
typeof(ans)

Int64

In [15]:
ans isa Int64

true

In [17]:
ans isa Integer

true

In [18]:
Int64 <: Number

true

In [19]:
supertype(Int64)

Signed

## Variables

In [2]:
my_answer = 42
typeof(my_answer)

Int64

In [1]:
my_pi = 3.14159
typeof(my_pi)

Float64

In [4]:
🧐 = "I will remembah!"
typeof(🧐)

String

In [5]:
my_answer = "forty two"
typeof(my_answer)

String

### Math Symbols

> In the Julia REPL and several other Julia editing environments, you can type many Unicode math symbols by typing the backslashed LaTeX symbol name followed by tab. For example, the variable name δ can be entered by typing \delta-tab, or even α̂⁽²⁾ by \alpha-tab-\hat- tab-\^(2)-tab. (If you find a symbol somewhere, e.g. in someone else's code, that you don't know how to type, the REPL help will tell you: just type ? and then paste the symbol.)

Source: https://docs.julialang.org/en/v1/manual/variables/

In [6]:
ϵ = 0.000001

1.0e-6

In [7]:
α̂ = 0.4

0.4

### Destructuring assignment
Iterators on the RHS will supply values to the LHS. Any excess values they generate are discarded.

In [8]:
(a, b, c) = 1:10
println("a = $a, b = $b, c = $c")

a = 1, b = 2, c = 3


In [9]:
x = 10
y = 20
x, y = y, x
println("x = $x, y = $y")

x = 20, y = 10


### Throwaway Variables
Just like in Python, _ variables are throwaway write-only variables. Unlike Python, I can have as many underscores as I want.

In [10]:
x, _ = size([2 2; 1 1])
println(x)

y, ______ = size([2 2; 1 1; 0 0])
println(y)

2
3


### Slurping
If the last symbol in the assignment list is suffixed by `...` (known as slurping), then it will be assigned a collection or lazy iterator of the remaining elements of the right-hand side iterator:

In [11]:
a, b... = "hello"

"hello"

In [12]:
a

'h': ASCII/Unicode U+0068 (category Ll: Letter, lowercase)

In [13]:
b

"ello"

In [14]:
a, b..., c = 1:5

1:5

In [15]:
a

1

In [16]:
b

3-element Vector{Int64}:
 2
 3
 4

In [17]:
c

5

## Commenting

In [18]:
# Single line comment

In [19]:
#=
This is a multi-line
comment.
=#

## Convert

* Use the [convert](https://docs.julialang.org/en/v1/base/base/#Base.convert) function.
* Use the [parse](https://docs.julialang.org/en/v1/base/numbers/#Base.parse) function.
* Use the [tryparse](https://docs.julialang.org/en/v1/base/numbers/#Base.tryparse) function.

In [1]:
tp = 3.0
typeof(tp)

Float64

In [2]:
tp2 = convert(Int, tp)

3

In [3]:
println(typeof(tp))
println(typeof(tp2))

Float64
Int64


In [4]:
@assert tp == 3
@assert tp2 == 3.0

In [2]:
try
    convert(Int, my_pi)
catch e
    @assert e isa InexactError
    println("Got InexactError")
end

Got InexactError


In [6]:
one_third = 1 / 3

0.3333333333333333

In [7]:
typeof(one_third)

Float64

In [8]:
convert(Float32, one_third)

0.33333334f0

In [9]:
convert(BigFloat, one_third)

0.333333333333333314829616256247390992939472198486328125

In [10]:
try
    convert(Int64, "1")
catch e
    @assert e isa MethodError
    println("Got MethodError")
end

Got MethodError


In [3]:
one = parse(Int64, "1")

1

In [4]:
try
    parse(Int, "1.2")
catch e
    @assert e isa ArgumentError
    println("Got ArgumentError")
end

Got ArgumentError


In [ ]:
# Instead of throwing an error, tryparse will return nothing
one = tryparse(Int, "1.1")

In [6]:
typeof(one)

Nothing

## Getting Help

The following does not work in VS Code notebook but will work in normal standard browser based notebooks and the Julia REPL.

```
?convert
help?> convert
search: convert Base.cconvert collect const

convert(T, x)

Convert x to a value of type T.

If T is an Integer type, an InexactError will be raised if x is not representable by T, for example if x is not integer-valued, or is outside the
range supported by T.

Examples
≡≡≡≡≡≡≡≡
....
```

## Numeric Literal Co-efficients

Ref: https://docs.julialang.org/en/v1/manual/integers-and-floating-point-numbers/#man-numeric-literal-coefficients

The basic idea is that I can write expressions like $2x + 3$ just like in math.

In [36]:
f(x) = 2x + 3

f (generic function with 1 method)

In [37]:
f(2)

7

I can also write exponential functions or polynomials more elegantly than in other languages. $5x^2 + 3x + 1$ can be written as -

In [38]:
g(x) = 5x^2 + 3x + 1

g (generic function with 1 method)

In [39]:
g(2)

27

But when dealing with exponents there is a subtle rule I need to keep in mind. If I want to write $2x^3$, how do I write it? The intuitive answer is `2x^3`. But why doesn't this mean $(2x)^3$? When a numeric literal coefficient appears **after** an exponentiation operator (^), the coefficient acts as a complete unit for the exponent. But when it appears **before** an exponentiation, the exponentiation binds more tightly to its immediate operand.

##### Summary:

* `2^3x` → base is 2, exponent is 3x (the whole thing), mathematically it is $2^{3x}$
* `2x^3` → coefficient is 2, the x gets cubed, then multiply, mathematically it is $2x^3$

The intuitive answer is the correct one here.

## Strings

Ref: https://docs.julialang.org/en/v1/base/strings/

This notebook is not exhaustive. I only included functions that I think I use on a semi-regular basis. I have skipped the more esoteric functions. I have also skipped regex even though I use it on a semi-regular basis, out of laziness. I have however included a few simple regex related functions.

### String Creation
  * double and tript quotes for strings, no special consideration except easier to embed double quotes in triple quoted strings.
  * Single quotes used for characters.
  * `@b_str`: to encode a string as binary bits
  * `@html_str`: Creates an HTML object
  * `@text_str`: Creates a text object

Strings are indexable so all the standard indexing things work

In [40]:
s1 = "I am a string"

"I am a string"

In [41]:
s2 = """I am also "string" :-)"""

"I am also \"string\" :-)"

In [42]:
s3 = """
Am I a multi-line string?
Just like in Python?
Lets find out.
"""

"Am I a multi-line string?\nJust like in Python?\nLets find out.\n"

In [43]:
s4 = "
Does it matter what kind of quotes I am using?
Will double-quotes also give me a multi-line string?
Lets find out.
"

"\nDoes it matter what kind of quotes I am using?\nWill double-quotes also give me a multi-line string?\nLets find out.\n"

In [44]:
typeof('a')

Char

In [47]:
'Single quotes will not work for strings. Only chars'

Base.Meta.ParseError: ParseError:
# Error @ /home/avilay/projects/github/learn-langs/learn-julia/jl_notebook_cell_df34fa98e69747e1a8f8a730347b8e2f_Y111sZmlsZQ==.jl:1:2
'Single quotes will not work for strings. Only chars'
#└─────────────────────────────────────────────────┘ ── character literal contains multiple characters

In [15]:
h = html"<h1>Learning Julia</h1>"

HTML{String}("<h1>Learning Julia</h1>")

In [16]:
typeof(h)

HTML{String}

In [12]:
v = b"12\x01\x02"

4-element Base.CodeUnits{UInt8, String}:
 0x31
 0x32
 0x01
 0x02

In [13]:
v[2]

0x32

In [17]:
t = text"Learning Julia"

Learning Julia

In [18]:
typeof(t)

Text{String}

In [45]:
lorem = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

"Lorem ipsum dolor sit amet, consectetur adipiscing elit."

In [46]:
lorem[5]

'm': ASCII/Unicode U+006D (category Ll: Letter, lowercase)

In [47]:
lorem[5:10]

"m ipsu"

In [49]:
lorem[begin:11]

"Lorem ipsum"

### String Interpolation

In [48]:
value = 42
msg = "And the answer is $value."

"And the answer is 42."

In [49]:
value_2 = 1
msg = "And the final answer is $(value - value_2) do you agree?"

"And the final answer is 41 do you agree?"

### String Concatenation
  * `string()` is equivalent to `*`
  * `repeat()` is equivalent to `^`

In [50]:
string(s1, s2)

"I am a stringI am also \"string\" :-)"

In [51]:
string("My name is APTG ", value, " Which stands for Avilay Parekh")

"My name is APTG 42 Which stands for Avilay Parekh"

In [52]:
s1 * s2

"I am a stringI am also \"string\" :-)"

In [53]:
"hi"^3

"hihihi"

In [54]:
repeat("hi", 3)

"hihihi"

### Misc

  * `reverse()`
  * `length()`
  * `sizeof()`

In [50]:
reverse(lorem)

".tile gnicsipida rutetcesnoc ,tema tis rolod muspi meroL"

In [51]:
length(lorem)

56

In [52]:
# Gives the number of bytes in the string
sizeof(lorem)

56

### Padding and Truncating
  * `lpad`
  * `rpad`
  * `ltruncate`
  * `rtruncate`
  * `ctruncate`

In [19]:
lpad("aptg", 12)

"        aptg"

In [20]:
lpad("aptg", 12, '.')

"........aptg"

In [53]:
rtruncate(lorem, 12)

"Lorem ipsum…"

### Stripping
  * `strip`, `lstrip`, `rstrip`: Default behavior is to strip leadding and/or trailing whitespace characters. But I can also specify any other character, or even a predicate.
  * `chop`: Chops the first or last n chars.
  * `chomp`: Convenience function to remove a single trailing newline from a string.

In [26]:
md = "## Heading Two"

"## Heading Two"

In [27]:
# Will strip off all `#` the beginning and end
strip(md, '#')

" Heading Two"

In [28]:
# Will strip off all # and <space>
strip(md, ('#', ' '))

"Heading Two"

In [29]:
str = "\nHello\r\n"

"\nHello\r\n"

In [30]:
strip(str)

"Hello"

In [31]:
chomp(str)

"\nHello"

In [32]:
chop(str, head=1, tail=2)

"Hello"

### Comparison
  * `==`
  * `cmp()`
  * `isless()` implemented for sorting, but I'll never need to use it directly.

In [33]:
"hello" == "hello"

true

In [34]:
cmp("hello", "hello")

0

In [35]:
cmp("hello", "hell")

1

In [36]:
cmp("hello", "hellothere")

-1

### Changing Case
  * `uppercase`
  * `lowercase`
  * `titlecase`
  * `uppercasefirst`
  * `lowercasefirst`

In [39]:
name = "avilay parekh"
abbr = "APTG"

"APTG"

In [40]:
uppercase(name)

"AVILAY PAREKH"

In [41]:
lowercase(abbr)

"aptg"

In [43]:
titlecase(name)

"Avilay Parekh"

In [44]:
uppercasefirst(name)

"Avilay parekh"

### Splitting and Joining
  * `split`, `eachsplit`: Returns a vector or an iterator.
  * `join`: 

In [54]:
split(lorem)

8-element Vector{SubString{String}}:
 "Lorem"
 "ipsum"
 "dolor"
 "sit"
 "amet,"
 "consectetur"
 "adipiscing"
 "elit."

In [55]:
split("hello.world.how.are.you?", '.')

5-element Vector{SubString{String}}:
 "hello"
 "world"
 "how"
 "are"
 "you?"

In [56]:
join(["avilay", "parekh"])

"avilayparekh"

In [58]:
join(["avilay", "parekh"], ", ")

"avilay, parekh"

### Finding
  * `findfirst`
  * `findnext`
  * `findlast`
  * `findprev`
  * `occursin(haystack)`, `occursin(needle, haystack)`: The first method returns a partial version of the second method.
  * `contains(needle)`,  `contains(haystack, needle)`: Same as `occursin`.
  * `startswith`
  * `endswith`

In [62]:
findfirst("dolor", lorem)

13:17

In [63]:
lookfor = occursin(lorem)

(::Base.Fix2{typeof(occursin), String}) (generic function with 2 methods)

In [64]:
lookfor("dolor")

true

In [65]:
lookin = contains("dolor")

(::Base.Fix2{typeof(contains), String}) (generic function with 2 methods)

In [66]:
lookin(lorem)

true

In [69]:
startswith(lorem, "Lorem")

true

### Query
  * `iscntrl`
  * `isdigit`
  * `isletter`
  * `islowercase`
  * `isnumeric`
  * `isprint`
  * `ispunct`
  * `isspace`
  * `isuppercase`

## Using Non-Standard Modules

For a detailed understanding of how modules work and how to author your own packages and modules, look at 2_Modules.md

In [1]:
using Dates: Date, today

In [56]:
dt = today()

2025-11-29

In [57]:
typeof(dt)

Date

In [58]:
Date(2026, 1, 30)

2026-01-30

## Tuples

  * Can have mixed types.
  * Are immutable.
  * Can be expressed as name-value pairs.
  * [NamedTuples](https://docs.julialang.org/en/v1/manual/types/#Named-Tuple-Types) also exist, but not documented in this notebook.

In [59]:
tpl = ("this", "is", "a", "tuple")

("this", "is", "a", "tuple")

In [60]:
typeof(tpl)

NTuple{4, String}

In [61]:
tpl[1] = "that"

MethodError: MethodError: no method matching setindex!(::NTuple{4, String}, ::String, ::Int64)
The function `setindex!` exists, but no method is defined for this combination of argument types.

In [62]:
tpl2 = ("NVDA", 190.17)

("NVDA", 190.17)

In [63]:
typeof(tpl2)

Tuple{String, Float64}

In [64]:
nvda = (stock="NVDA", price=190.17, recorded_on=today())

(stock = "NVDA", price = 190.17, recorded_on = Date("2025-11-29"))

In [65]:
typeof(nvda)

@NamedTuple{stock::String, price::Float64, recorded_on::Date}

In [66]:
# Can access by position...
nvda[1]

"NVDA"

In [67]:
# ...and also by name
nvda.stock

"NVDA"

## Pair

In [34]:
x = "APPL" => 278.28

"APPL" => 278.28

In [35]:
typeof(x)

Pair{String, Float64}

## Dictionaries

  * Are mutable
  * Can have mixed type keys and mixed type values

In [2]:
nvda2 = Dict(
    "stock" => "NVDA",
    "price" => 190.17,
    "recorded_on" => today()
)

Dict{String, Any} with 3 entries:
  "price"       => 190.17
  "stock"       => "NVDA"
  "recorded_on" => Date("2025-12-15")

In [3]:
name = Dict("first" => "Avilay", "last" => "Parekh")

Dict{String, String} with 2 entries:
  "first" => "Avilay"
  "last"  => "Parekh"

In [4]:
slots = Dict("first" => 1, 2 => "second")

Dict{Any, Any} with 2 entries:
  2       => "second"
  "first" => 1

In [5]:
# Dict comprehension
tp = Dict(name => rand(1:10) for name in ["APTG", "Lalji", "Avilay"])

Dict{String, Int64} with 3 entries:
  "Lalji"  => 4
  "Avilay" => 4
  "APTG"   => 8

In [6]:
v = get(tp, "APTG", -1)

8

In [7]:
tp

Dict{String, Int64} with 3 entries:
  "Lalji"  => 4
  "Avilay" => 4
  "APTG"   => 8

In [8]:
v = get(tp, "Lalo", -1)

-1

In [9]:
tp

Dict{String, Int64} with 3 entries:
  "Lalji"  => 4
  "Avilay" => 4
  "APTG"   => 8

In [10]:
w = get!(tp, "Lalo", 999)

999

In [11]:
tp

Dict{String, Int64} with 4 entries:
  "Lalo"   => 999
  "Lalji"  => 4
  "Avilay" => 4
  "APTG"   => 8

In [12]:
delete!(tp, "Lalo")

Dict{String, Int64} with 3 entries:
  "Lalji"  => 4
  "Avilay" => 4
  "APTG"   => 8

In [13]:
nvda2["stock"]

"NVDA"

In [14]:
nvda2["price"] = 191.0
nvda2

Dict{String, Any} with 3 entries:
  "price"       => 191.0
  "stock"       => "NVDA"
  "recorded_on" => Date("2025-12-15")

In [15]:
nvda2["qty"] = 100
nvda2

Dict{String, Any} with 4 entries:
  "price"       => 191.0
  "stock"       => "NVDA"
  "recorded_on" => Date("2025-12-15")
  "qty"         => 100

In [16]:
getkey(nvda2, "price", "none")

"price"

In [17]:
getkey(nvda2, "volume", "none")

"none"

In [18]:
recorded_on = pop!(nvda2, "recorded_on")

2025-12-15

In [19]:
nvda2

Dict{String, Any} with 3 entries:
  "price" => 191.0
  "stock" => "NVDA"
  "qty"   => 100

In [20]:
push!(nvda2, "timestamp" => 1763632383)

Dict{String, Any} with 4 entries:
  "price"     => 191.0
  "stock"     => "NVDA"
  "timestamp" => 1763632383
  "qty"       => 100

In [21]:
myphonebook = Dict(
    "Jenny" => "867-5309",
    "Ghostbusters" => "555-2368"
)

Dict{String, String} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

In [22]:
# Cannot change the type after-the-fact
try
    myphonebook["Emergency"] = 911
catch err
    @assert err isa MethodError
    println(err)
end

MethodError(convert, (String, 911), 0x0000000000009745)


In [23]:
myphonebook_2 = Dict{String,Union{String,Number}}(
    "Jenny" => "867-5309",
    "Ghostbusters" => "555-2368"
)

Dict{String, Union{Number, String}} with 2 entries:
  "Jenny"        => "867-5309"
  "Ghostbusters" => "555-2368"

In [24]:
myphonebook_2["Emergency"] = 911
myphonebook_2

Dict{String, Union{Number, String}} with 3 entries:
  "Jenny"        => "867-5309"
  "Emergency"    => 911
  "Ghostbusters" => "555-2368"

### Check Membership
Multiple ways to check if a key is in a dictionary

In [25]:
cookies = Dict(
    "Chocolate Chip" => 200,
    "Oatmeal Raisin" => 180
)

Dict{String, Int64} with 2 entries:
  "Chocolate Chip" => 200
  "Oatmeal Raisin" => 180

In [26]:
haskey(cookies, "Chocolate Chip")

true

In [28]:
"Chocolate Chip" in keys(cookies)

true

In [29]:
# the ∈ is typed by pressing \in followed by a tab.
"Chocolate Chip" ∈ keys(cookies)

true

### Iterators

In [30]:
keys(cookies)

KeySet for a Dict{String, Int64} with 2 entries. Keys:
  "Chocolate Chip"
  "Oatmeal Raisin"

In [32]:
for key in keys(cookies)
    println("Cookie name: $keys")
end

Cookie name: keys
Cookie name: keys


In [33]:
values(cookies)

ValueIterator for a Dict{String, Int64} with 2 entries. Values:
  200
  180

In [34]:
a = Dict("foo" => 0.0, "bar" => 42.0)
b = Dict("baz" => 17, "bar" => 4711)

# merging the two dicts will overwrite bar key
merge(a, b)

Dict{String, Float64} with 3 entries:
  "bar" => 4711.0
  "baz" => 17.0
  "foo" => 0.0

In [35]:
# If I don't want to overwrite, I can use mergewith
mergewith(+, a, b)

Dict{String, Float64} with 3 entries:
  "bar" => 4753.0
  "baz" => 17.0
  "foo" => 0.0

In [36]:
for (k, v) in cookies
    println("$k => $v")
end

Chocolate Chip => 200
Oatmeal Raisin => 180


In [37]:
keytype(cookies)

String

In [39]:
valtype(cookies)

Int64

## Set

In [1]:
s = Set("aaBca")

Set{Char} with 3 elements:
  'a'
  'c'
  'B'

In [2]:
push!(s, 'b')

Set{Char} with 4 elements:
  'a'
  'c'
  'b'
  'B'

In [3]:
'a' ∈ s

true

In [11]:
s1 = Set([1, 2, 3])
s2 = Set([2, 3])
s2 ⊆ s1

true

In [13]:
# For some reason a strict subset function is not implemented
s2 ⊂ s1

UndefVarError: UndefVarError: `⊂` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

`union()` and `intersect()` functions work with all sorts of iterables including sets. I am showing examples of `union` but `intersect` works the same way.

In [4]:
union([1, 2], [3])

3-element Vector{Int64}:
 1
 2
 3

In [5]:
union([4 2 3 4 4], 1:3, 3.0)

4-element Vector{Float64}:
 4.0
 2.0
 3.0
 1.0

In [6]:
(0, 0.0) ∪ (-0.0, NaN)

3-element Vector{Real}:
   0
  -0.0
 NaN

In [9]:
union(Set([1, 2]), 2:3)

Set{Int64} with 3 elements:
  2
  3
  1

## Vectors aka Dynamic Arrays

  * Mutable
  * Can have mixed types
  * 1-based indexing
  * Negative indexes don't work
  * Slices are inclusive on both sides

1D arrays are called `Vector`s, 2D arrays are called `Matrix`, N-D arrays are called `Array`. See 3_Arrays.ipynb for more details. This section deals with `Vector`s as they are traditionally used as arrays in other programming languages.

In [7]:
portfolio = ["NVDA", "MSFT", "META", "APPL", "U"]

5-element Vector{String}:
 "NVDA"
 "MSFT"
 "META"
 "APPL"
 "U"

In [8]:
portfolio[1]

"NVDA"

In [9]:
portfolio[2:4]

3-element Vector{String}:
 "MSFT"
 "META"
 "APPL"

I have come across three ways to append to a vector -
  1. `[portfolio..., "GOOG"]`
  2. `[portfolio; "GOOG"]`
  3. `push!(portfolio, "GOOG")`

In [11]:
[portfolio..., "GOOG"]

6-element Vector{String}:
 "NVDA"
 "MSFT"
 "META"
 "APPL"
 "U"
 "GOOG"

In [13]:
[portfolio; "GOOG"]

6-element Vector{String}:
 "NVDA"
 "MSFT"
 "META"
 "APPL"
 "U"
 "GOOG"

In [6]:
length(portfolio)

5

In [7]:
portfolio[end]

"U"

In [8]:
portfolio[begin]

"NVDA"

In [92]:
prices = [190.17, 510.18, 609.46, 272.41]

4-element Vector{Float64}:
 190.17
 510.18
 609.46
 272.41

In [93]:
std_bases = [1 0; 0 1]

2×2 Matrix{Int64}:
 1  0
 0  1

In [94]:
std_bases_2 = [[1, 0], [0, 1]]

2-element Vector{Vector{Int64}}:
 [1, 0]
 [0, 1]

In [95]:
mixed = [1, "hello", today()]

3-element Vector{Any}:
 1
  "hello"
  2025-11-29

In [96]:
portfolio[4] = "U"
portfolio

5-element Vector{String}:
 "NVDA"
 "MSFT"
 "META"
 "U"
 "U"

In [97]:
push!(portfolio, "APPL")

6-element Vector{String}:
 "NVDA"
 "MSFT"
 "META"
 "U"
 "U"
 "APPL"

In [98]:
last_stock = pop!(portfolio)

"APPL"

In [99]:
portfolio

5-element Vector{String}:
 "NVDA"
 "MSFT"
 "META"
 "U"
 "U"

In [100]:
rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.593058  0.76334    0.528264
 0.452274  0.724608   0.924325
 0.649783  0.827101   0.0553985
 0.462025  0.0130469  0.842273

[:, :, 2] =
 0.252671  0.616724  0.295999
 0.745163  0.725497  0.713165
 0.800605  0.712931  0.477438
 0.856327  0.290146  0.35626

In [102]:
fib = [1, 1, 2, 3, 5, 8, 13]
nums = fib
println("fib = ", fib)
println("nums = ", nums)

fib = [1, 1, 2, 3, 5, 8, 13]
nums = [1, 1, 2, 3, 5, 8, 13]


In [103]:
nums[1] = 404
println("fib = ", fib)
println("nums = ", nums)

fib = [404, 1, 2, 3, 5, 8, 13]
nums = [404, 1, 2, 3, 5, 8, 13]


In [104]:
# Use copy to avoid reference sharing
fib = [1, 1, 2, 3, 5, 8, 13]
copy_of_fib = copy(fib)
println("fib = ", fib)
println("copy_of_fib = ", copy_of_fib)

fib = [1, 1, 2, 3, 5, 8, 13]
copy_of_fib = [1, 1, 2, 3, 5, 8, 13]


In [105]:
copy_of_fib[1] = 404
println("fib = ", fib)
println("copy_of_fib = ", copy_of_fib)

fib = [1, 1, 2, 3, 5, 8, 13]
copy_of_fib = [404, 1, 2, 3, 5, 8, 13]


## Comparison Operators

  * Value equality: `==` compares the values of two objects, they don't have to be exactly the same.
  * Identity equality : `===` compares the structures or memory location of the two objects. It is not just memory locations, because for immutable composite types, the memory location does not have to be the same.
  * Value inequality: `!=` or $\neq$ is the opposite of the value equality operator.
  * Identity inequality: `!==` is the opposite of identity equality.
  * Approximately equal: $\approx$ is shorthand for the `isapprox(x, y; atol, rtol)` function to compare floating point numbers.
  * Less than and greater than: `<=` or $\leq$ and `>=` or $\geq$ behave as expected.

In [1]:
ary1 = [1, 2, 3]
ary2 = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [2]:
ary1 == ary2

true

In [3]:
ary1 === ary2

false

In [4]:
5 == 5.0

true

In [5]:
5 === 5.0

false

In [7]:
1.21 ≈ 1.210000001

true

In [8]:
struct Cookie
    flavor::String
    calories::Int
end

In [9]:
c1 = Cookie("Chocolate Chip", 200)
c2 = Cookie("Chocolate Chip", 200)

Cookie("Chocolate Chip", 200)

In [10]:
c1 == c2

true

In [ ]:
# Identity will also evaluate to true because Cookie is an immutable object
c1 === c2

true

## Loops

In [106]:
n = 1234
digits = []
while n > 10
    digit = n % 10
    push!(digits, digit)
    n = div(n, 10)
end
push!(digits, n)
print(digits)

Any[4, 3, 2, 1]

In [107]:
for i in 1:5
    println("i = ", i)
end

i = 1
i = 2
i = 3
i = 4
i = 5


In [108]:
portfolio = ["MSFT", "META", "NVDA", "U", "APPL"]
for stock in portfolio
    println("stock = ", stock)
end

stock = MSFT
stock = META
stock = NVDA
stock = U
stock = APPL


In [109]:
# i is the inner loop, i.e., it goes faster
for j in 1:3, i in 1:3
    println("i = ", i, "; j = ", j)
end

i = 1; j = 1
i = 2; j = 1
i = 3; j = 1
i = 1; j = 2
i = 2; j = 2
i = 3; j = 2
i = 1; j = 3
i = 2; j = 3
i = 3; j = 3


In [110]:
# i is still the inner loop
# the matrix is filled in row-major form
C = [10 * j + i for j in 1:3, i in 7:9]

3×3 Matrix{Int64}:
 17  18  19
 27  28  29
 37  38  39

In [1]:
sqs = [i^2 for i in 1:10 if i % 2 == 0]

5-element Vector{Int64}:
   4
  16
  36
  64
 100

## Conditions

In [112]:
n = 33

if (n % 3 == 0) && (n % 5 == 0)
    println("Fizz Buzz")
elseif n % 3 == 0
    println("Fizz")
elseif n % 5 == 0
    println("Buzz")
else
    println(n)
end

Fizz


In [113]:
a = n > 15 ? "large" : "small"

"large"