# Arrays

[Numpy to Julia cheatsheet](https://cheatsheets.quantecon.org/)

This note will also cover `Vector` and `Matrix` types.

## Declaration

### Syntax and Types

General syntax seems to be -
  * Commas are used for enumerating elements
  * Semicolons and newlines are used for stacking elements vertically
  * Spaces and double semicolons are used for stacking elements horizontally
  
$\mathcal{Vector}$ are used for 1D *column* vectors. Either commas or semicolons can be used to declare these. If I want to create a *row* vector, I'll have to use spaces. Furthermore I'll end up with a type of $1 \times 2$ $\mathcal{Matrix}$.

$\mathcal{Matrix}$ are used for 2D list of numbers. Here spaces are used for defining a row, and rows are separated (or stacked on top of each other) by semicolons. If I try to seperate a row by commas instead, I'll end up with the outer type being a vector.

$\mathcal{Array}$ are used for multi-dimensional tensors.

It is not possible to define jagged tensors.

The repr of a variable has the shape of the data as well as its type in there. E.g., when I see `3-element Vector{Int64}`, it means that the `typeof()` function will give me `Vector{Int64}`.

### Initialization

##### 1D Column Vector

In [2]:
v = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [3]:
# This syntax seems to be the same as above
u = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [4]:
@assert v == u

In [6]:
w = [
    1
    2
    3
]

3-element Vector{Int64}:
 1
 2
 3

In [7]:
@assert v == w

##### 1D row vector of type Matrix

In [4]:
r = [1 2]

1×2 Matrix{Int64}:
 1  2

In [5]:
# Matrix{Int64} is just an alias for Array{Int64, 2} as can be seen when we
# explicitly print its type
# Array{Int64, 2} stands for a 2D array with 64 bit ints.
typeof(r)

Matrix{Int64} (alias for Array{Int64, 2})

##### 2D Matrix

In [ ]:
# Row separator is a ;
A = [
    1 2 3;
    4 5 6
]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [ ]:
# Row separator is a newline
B = [
    1 2 3
    4 5 6
]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In case I want a different data type than what Julia gives, I can specify it like so -

In [99]:
Int8[
    1 2 3
    4 5 6
]

2×3 Matrix{Int8}:
 1  2  3
 4  5  6

Lets verify that `u` and `v` are indeed column vectors.

In [7]:
A * v

2-element Vector{Int64}:
 14
 32

In [8]:
A * u

2-element Vector{Int64}:
 14
 32

Further, lets verify that `r` is a row vector.

In [9]:
r * A

1×3 Matrix{Int64}:
 9  12  15

In [10]:
# I can declare A with the intermediate square brackets like numpy if I like.
A = [
    [1 2 3];
    [4 5 6]
]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [11]:
A = reshape(Vector(1:6), 3, 2)

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

In [12]:
# Not using the Vector constructor (cast?) will give me a different type -
# reshape(::UnitRange{Int64}, 3, 2) with eltype Int64
A = reshape(1:6, 3, 2)

3×2 reshape(::UnitRange{Int64}, 3, 2) with eltype Int64:
 1  4
 2  5
 3  6

##### N-D Tensor of type Array
I can use `reshape` with ranges, `zeros`, `fill`, etc. or use the `Array{T}(undef, dims)` syntax. See [Multi-dimensional Arrays](https://docs.julialang.org/en/v1/manual/arrays/) for a full list of such functions.

In [13]:
# Its type is Array{Int64, 3} which stands for a 3D array with 64 bit ints.
A = reshape(Vector(1:12), 3, 2, 2)

3×2×2 Array{Int64, 3}:
[:, :, 1] =
 1  4
 2  5
 3  6

[:, :, 2] =
 7  10
 8  11
 9  12

`Array{Float32}(undef, (4, 3, 2))` will allocate memory for a $4 \times 3 \times 2$ tensor of 4-byte floats. The `undef` tells Julia to not bother with cleaning up the memory. So the allocated memory might have garbage left by its previous occupants. While these are useful for creating tensors with more than 2 dimensions, I can ofcourse use it for 1- or 2-D lists as well.

In [14]:
X = Array{Float32}(undef, (4, 3, 2))

4×3×2 Array{Float32, 3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [15]:
# Even though I said Array, I still get a matrix because this is 2D. I can also use the `Matrix` type here to get the same result
X = Array{Float32}(undef, (3, 2))

3×2 Matrix{Float32}:
 -6.30091f25   4.571f-41
  4.571f-41   -9.25041f19
 -9.23543f19   4.571f-41

In [16]:
X = Matrix{Float32}(undef, (3, 2))

3×2 Matrix{Float32}:
 -6.19509f25    4.571f-41
  4.571f-41    -9.4295f19
 -0.000629819   4.571f-41

In [17]:
# Same with Vector
X = Array{Float32}(undef, 2)

2-element Vector{Float32}:
 4.0f-45
 0.0

## Visualization

### 1D and 2D lists

Lets get the easy ones out of the way first.

Vectors (aka column vectors), are defined as `u = [1, 2]` or `v = [1; 2]` and they can be visualized as follows -
$$
\begin{bmatrix}
1 \\
2
\end{bmatrix}
$$

Row vectors (aka $1 \times n$ Matrix) are defined as `r = [1 2]` and can be visualized as -
$$
\left[ 1 \; 2 \right]
$$

Matrix (aka 2D lists) defined as -
```
M = [
    3 5 7;
    4 6 8
]
```
and can be visualized as -
$$
\begin{bmatrix}
3 & 5 & 7 \\
4 & 6 & 8 \\
\end{bmatrix}
$$

### N-D Arrays
Just like in numpy, the visualization is exactly the way the arrays are printed. When we print out a $4 \times 3 \times 2$ numpy array, we can see that it is made up of $4$ chunks of $3 \times 2$ blocks . 

```
array([[[0.7253, 0.3631],
        [0.5012 , 0.1484],
        [0.2274 , 0.1282]],

       [[0.1915, 0.9439 ],
        [0.3736, 0.5736 ],
        [0.8890, 0.2769]],

       [[0.3835, 0.8049],
        [0.0638, 0.2258],
        [0.1412 , 0.0056]],

       [[0.3292, 0.0582],
        [0.2112 , 0.3427],
        [0.9275, 0.2823]]])
```

And when we print out a Julia array we get $2$ chunks of $4 \times 3$ blocks.

```
4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.1142  0.7996   0.0590
 0.7842  0.8741  0.5310
 0.2194   0.8996    0.9407
 0.9997  0.1919  0.8051

[:, :, 2] =
 0.7866  0.7501  0.3640
 0.2116  0.7015   0.1641
 0.1814  0.4969  0.2976
 0.2115  0.8125  0.3476
```

In [9]:
A = reshape(1:8, 2, 2, 2)
A

2×2×2 reshape(::UnitRange{Int64}, 2, 2, 2) with eltype Int64:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

When indexing, I think of the first two dimensions as "special". The first dimension is "row", the second dimension is "column", and the rest of the dimensions are "blocks".

In [ ]:
# This will get me the first row-all columns, for all the blocks.
A[1, :, :]

2×2 Matrix{Int64}:
 1  5
 3  7

In [ ]:
# This will get me all rows-first column, for all the blocks
A[:, 1, :]

2×2 Matrix{Int64}:
 1  5
 2  6

In [12]:
# This will get me the first block
A[:, :, 1]

2×2 Matrix{Int64}:
 1  3
 2  4

## Concatenation

The main function to use is [`cat(A...; dims)`](https://docs.julialang.org/en/v1/base/arrays/#Base.cat). There are a bunch of convenience functions like `vcat`, `hcat`, etc. But the easiest way to concat is to use a combination of newlines/semicolons and spaces/double-semicolons for this. Use as many semicolons as the dimension number I want to concatenate on, e.g., to concatenate on the third dimension use `;;;` and so on. A single semicolon will concatenate on the first dimension, i.e., it will stack rows on top of each other. This is the same behavior as that of newlines. A double semicolon will concatenate on the second dimension, i.e., it will stack columns next to each other. This is the same as using spaces.

In [20]:
# Column vector
x = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [23]:
# Will stack two xs on top of each other
[x; x]

6-element Vector{Int64}:
 1
 2
 3
 1
 2
 3

In [36]:
# This will also stack two xs on top of each other
[
    x
    x
]

6-element Vector{Int64}:
 1
 2
 3
 1
 2
 3

In [25]:
# Will stack two xs next to each other
[x x]

3×2 Matrix{Int64}:
 1  1
 2  2
 3  3

In [37]:
# This will also stack two xs next to each other
[x;; x]

3×2 Matrix{Int64}:
 1  1
 2  2
 3  3

In [42]:
B = [
    9 11
    10 12
]

2×2 Matrix{Int64}:
  9  11
 10  12

In [43]:
# This will stack A on top of B
cat(A, B, dims=3)

2×2×3 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

[:, :, 3] =
  9  11
 10  12

In [44]:
[A;;; B]

2×2×3 Array{Int64, 3}:
[:, :, 1] =
 1  3
 2  4

[:, :, 2] =
 5  7
 6  8

[:, :, 3] =
  9  11
 10  12

I might think that `[A;B]` will stack all of `A` on top of `B`, but that is not true. It will try to concatenate on the first dimension. And in order to do that, all the other dimensions must match, i.e., $A \in \mathcal R^{2 \times 2 \times 2}$ and $B \in \mathcal R^{2 \times 2}$ or equivalently $B \in \mathcal R^{2 \times 2 \times 1}$. dim-1 does not need to match, that is the one that is going to be concatenated. dim-2 does match but dim-3 does not. So this operation will fail. The reason concatenation on the third dimension succeeds is because the first two dims match. 

Lets reshape `B` so that the last two dims match `A`. Note that because Julia is column-major, the columns are split into different dimensions. So if I was expecting the output to be -

$$
\begin{bmatrix}
\begin{bmatrix}
1 & 3 \\
2 & 4 \\
9 & 11
\end{bmatrix} \\
\begin{bmatrix}
5 & 7 \\
6 & 8 \\
10 & 12
\end{bmatrix}
\end{bmatrix}
$$

That is NOT GOING TO HAPPEN!

Reshaping `B` will split its columns into different dimensions, so I'll get the column elements stacked under the rows of each block of `A`.

In [48]:
# Lets reshape B so the last two dims match A
C = reshape(B, 1, 2, 2)

1×2×2 Array{Int64, 3}:
[:, :, 1] =
 9  10

[:, :, 2] =
 11  12

In [47]:
# Now everything works!
[A; C]

3×2×2 Array{Int64, 3}:
[:, :, 1] =
 1   3
 2   4
 9  10

[:, :, 2] =
  5   7
  6   8
 11  12

If I want to concatenate on the second dimension, i.e., I want to stack the elements of `B` horizontally onto each block of `A`, i.e., I want the output -

$$
\begin{bmatrix}
\begin{bmatrix}
1 & 3 & 9 \\
2 & 4 & 10 \\
\end{bmatrix} \\
\begin{bmatrix}
5 & 7 & 11 \\
6 & 8 & 12 \\
\end{bmatrix}
\end{bmatrix}
$$

Here again `B`'s columns are split into different dimensions, so each original column is stacked horinzontally to the columns in each block of `A`.

In [50]:
D = reshape(B, 2, 1, 2)

2×1×2 Array{Int64, 3}:
[:, :, 1] =
  9
 10

[:, :, 2] =
 11
 12

In [52]:
[A;; D]

2×3×2 Array{Int64, 3}:
[:, :, 1] =
 1  3   9
 2  4  10

[:, :, 2] =
 5  7  11
 6  8  12

## Indexing

Julia stores its multidim arrays in column major form, as opposed to numpy which uses the row-major form. There are two main ways to index into an array -
  * Cartesian indexing: Here I have to specify a value for each dimension. Each value can be a scalar, array, range, booleans, or `:`.
  * Linear indexing: Here I specify a single value. This single value can be a scalar or another array.

### Linear Indexing

Conceptually, the array is first unravled in its col-major form, and the elements provided as the index are chosen. For example if I say `A[3]`, it will give me the third element in the unravled array. If I say `A[[3, 50, 43]]` it will give me another array that looks like `[A[3], A[50], A[43]]`. The output will take the shape of the input index.

In [2]:
A = reshape(1:(2*3*3*2*2), 2, 3, 3, 2, 2)

2×3×3×2×2 reshape(::UnitRange{Int64}, 2, 3, 3, 2, 2) with eltype Int64:
[:, :, 1, 1, 1] =
 1  3  5
 2  4  6

[:, :, 2, 1, 1] =
 7   9  11
 8  10  12

[:, :, 3, 1, 1] =
 13  15  17
 14  16  18

[:, :, 1, 2, 1] =
 19  21  23
 20  22  24

[:, :, 2, 2, 1] =
 25  27  29
 26  28  30

[:, :, 3, 2, 1] =
 31  33  35
 32  34  36

[:, :, 1, 1, 2] =
 37  39  41
 38  40  42

[:, :, 2, 1, 2] =
 43  45  47
 44  46  48

[:, :, 3, 1, 2] =
 49  51  53
 50  52  54

[:, :, 1, 2, 2] =
 55  57  59
 56  58  60

[:, :, 2, 2, 2] =
 61  63  65
 62  64  66

[:, :, 3, 2, 2] =
 67  69  71
 68  70  72

In [3]:
A[[3, 50, 43]]

3-element Vector{Int64}:
  3
 50
 43

In [4]:
A[[3 50; 43 10]]

2×2 Matrix{Int64}:
  3  50
 43  10

### Cartesian Indexing
This is the more familiar form of indexing. Unlike numpy where `A[1]` is shortcut for `A[1,:]`, in Julia I have to specify each and every dimension with a few exceptions.

In [5]:
# Using all scalars
A[1, 2, 2, 2, 2]

63

In the below example where my index is `[2, 2:3, 2, 2, 2]`, to begin with I ignore the first two dimensions and focus on which blocks to select. So I choose the `[:, :, 2, 2, 2]` block which is -
$$
\begin{matrix}
61 & 63 & 65 \\
62 & 64 & 66
\end{matrix}
$$

Then looking at the first two dims I know that I want the $2^{nd}$ row and all columns ranging from $[2, 3]$, which is just the $2^{nd}$ and $3^{rd}$ columns, which gives me the elements $64$ and $66$.

In [7]:
A[2, 2:3, 2, 2, 2]

2-element Vector{Int64}:
 64
 66

In the below example `[:, 3, [1, 3], 2, 2]` one of the dimensions is specified as an array, but this does not mean Julia is going to use linear indexing here. The array is just a way to cherry-pick elements from that dimension. As before lets ignore the first two dimensions. I need the `[:, :, 1, 2, 2]` and `[:, :, 3, 2, 2]` blocks -

$$
\begin{bmatrix}
55 & 57 & 59 \\
56 & 58 & 60 \\
\end{bmatrix}
$$

and 

$$
\begin{bmatrix}
67 & 69 & 71 \\
68 & 70 & 72
\end{bmatrix}
$$

From here I need all the rows and the third column from each -

$$
\begin{bmatrix}
59 \\
60
\end{bmatrix}
$$

and 

$$
\begin{bmatrix}
71 \\
72
\end{bmatrix}
$$

There are two arrays in the index, so they will determine the shape of the output. The first one is `:` which is $2 \times 1$ and the second one is `[1, 3]` which is also $2 \times 1$, so the output will be $2 \times 2$. I admit I don't fully understand how the output is arranged in my pre-frontal cortex, but I have an intuitive feel for it, and for the time being that will have to do.

In [13]:
A[:, 3, [1, 3], 2, 2]

2×2 Matrix{Int64}:
 59  71
 60  72

If I specify the 3rd dimension as `[1 3]` instead, this will give me a $1 \times 2$ that will need to be combined with $2 \times 1$ from `:` resulting in $2 \times 1 \times 2$

In [16]:
A[:, 3, [1 3], 2, 2]

2×1×2 Array{Int64, 3}:
[:, :, 1] =
 59
 60

[:, :, 2] =
 71
 72

This is more clear if I get rid of the one of the arrays in the index. 

In [17]:
A[1, 3, [1 3], 2, 2]

1×2 Matrix{Int64}:
 59  71

In [18]:
A[1, 3, [1, 3], 2, 2]

2-element Vector{Int64}:
 59
 71

In [19]:
A[:, 3, 1, 2, 2]

2-element Vector{Int64}:
 59
 60

The array inside the index can be multidim. The logic remains the same, blocks are cherry picked based on the indices in the index-array and then arranged based on the index-array's shape.

In [28]:
A[1, 3, [1 3; 2 3], 2, 2]

2×2 Matrix{Int64}:
 59  71
 65  71

In [29]:
A[:, 3, [1 3; 2 3], 2, 2]

2×2×2 Array{Int64, 3}:
[:, :, 1] =
 59  65
 60  66

[:, :, 2] =
 71  71
 72  72

### TODO
  * `CartesianIndex`
  * Concept of `view(A)`
  * Logical indexing
  * Converting from cartesian indexes to linear index
  * Indexed assignment
  * Iterating with `eachindex(A)`
  * Basic functions -
    - `eltype(A)`
    - `length(A)`
    - `ndims(A)`
    - `size(A[, n])`
    - `axes(A[, n])`
    - `vec(A)`
  * Concept of strides

In [44]:
A = rand(1:100, 3, 3)

3×3 Matrix{Int64}:
 71  52   80
 68  98   61
  1   6  100

In [45]:
i = CartesianIndex(1, 1)
j = CartesianIndex(2, 2)
k = CartesianIndex(3, 3)

CartesianIndex(3, 3)

In [46]:
A[[i, j, k]]

3-element Vector{Int64}:
  71
  98
 100

In [48]:
collect(axes(A, 2))

3-element Vector{Int64}:
 1
 2
 3

In [50]:
CartesianIndex.(axes(A, 1), axes(A, 2))

3-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 2)
 CartesianIndex(3, 3)

In [51]:
size(A)

(3, 3)

In [22]:
axes(A, 2)

Base.OneTo(3)

In [25]:
CartesianIndex(axes(A, 1))

MethodError: MethodError: no method matching CartesianIndex(::Base.OneTo{Int64})
The type `CartesianIndex` exists, but no method is defined for this combination of argument types when trying to construct it.

Closest candidates are:
  CartesianIndex(!Matched::NTuple{N, Integer}) where N
   @ Base multidimensional.jl:80
  CartesianIndex(!Matched::Tuple{Vararg{Union{Integer, CartesianIndex}}})
   @ Base multidimensional.jl:93
  CartesianIndex(!Matched::Integer...)
   @ Base multidimensional.jl:81
  ...


If I do want an initialized array then I should use the [`fill`](https://docs.julialang.org/en/v1/base/arrays/#Base.fill) function.

In [32]:
# Works the way numpy works
fill(2.7, 3, 2)

3×2 Matrix{Float64}:
 2.7  2.7
 2.7  2.7
 2.7  2.7

In [33]:
# Useful for creating 0-dim arrays
fill(2.7)

0-dimensional Array{Float64, 0}:
2.7

In [37]:
# b copies a reference to a
a = [1, 2, 3]
b = fill(a, 2)

2-element Vector{Vector{Int64}}:
 [1, 2, 3]
 [1, 2, 3]

In [38]:
# Any change in a is reflected in all the positions of b
push!(a, 4)
b

2-element Vector{Vector{Int64}}:
 [1, 2, 3, 4]
 [1, 2, 3, 4]

## Broadcasting

Broadcasting will apply a binary function (function that takes in two inputs) to each element of the 2 input arrays. This means that the arrays need to have the exact same shape, i.e., the number of dims should be the same, and the size of each dim should also be the same. If this is not the case, the `broadcast` function will try to replicate the values in a "sensible" manner to make the shapes the same. It works very similar to Python's broadcast, except the broadcasting replication blocks are from the left and not the right like in Python. For example if I need to broadcast a $2 \times 3 \times 1 \times 2 \times 2$ with a $2 \times 3 \times 3 \times 2 \times 2$ tensor, then main $2 \times 3$ matrix will be replicated thrice inside each of the four blocks.

Even though there is an explicit function called `broadcast`, people usually use the `.` operator syntactic sugar for this.

In [84]:
o = ones(Int, 2, 3, 3, 2, 2);

In [85]:
a = reshape(Vector(1:(2*3*1*2*2)), 2, 3, 1, 2, 2)

2×3×1×2×2 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 1  3  5
 2  4  6

[:, :, 1, 2, 1] =
 7   9  11
 8  10  12

[:, :, 1, 1, 2] =
 13  15  17
 14  16  18

[:, :, 1, 2, 2] =
 19  21  23
 20  22  24

Now if I broadcast `a` with `o`, then I expect to see the "main" matrices replicated thrice.

In [86]:
o .* a

2×3×3×2×2 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 1  3  5
 2  4  6

[:, :, 2, 1, 1] =
 1  3  5
 2  4  6

[:, :, 3, 1, 1] =
 1  3  5
 2  4  6

[:, :, 1, 2, 1] =
 7   9  11
 8  10  12

[:, :, 2, 2, 1] =
 7   9  11
 8  10  12

[:, :, 3, 2, 1] =
 7   9  11
 8  10  12

[:, :, 1, 1, 2] =
 13  15  17
 14  16  18

[:, :, 2, 1, 2] =
 13  15  17
 14  16  18

[:, :, 3, 1, 2] =
 13  15  17
 14  16  18

[:, :, 1, 2, 2] =
 19  21  23
 20  22  24

[:, :, 2, 2, 2] =
 19  21  23
 20  22  24

[:, :, 3, 2, 2] =
 19  21  23
 20  22  24

If the last dimension is missing, or is $1$, which all the same to Julia, the tensor will be "unsqueezed" in the last dimension and the entire outer block, which is the entirity of the tensor, will be replicated.

In [87]:
a = reshape(Vector(1:(2*3*3*2)), 2, 3, 3, 2)

2×3×3×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3  5
 2  4  6

[:, :, 2, 1] =
 7   9  11
 8  10  12

[:, :, 3, 1] =
 13  15  17
 14  16  18

[:, :, 1, 2] =
 19  21  23
 20  22  24

[:, :, 2, 2] =
 25  27  29
 26  28  30

[:, :, 3, 2] =
 31  33  35
 32  34  36

In [88]:
o .* a

2×3×3×2×2 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 1  3  5
 2  4  6

[:, :, 2, 1, 1] =
 7   9  11
 8  10  12

[:, :, 3, 1, 1] =
 13  15  17
 14  16  18

[:, :, 1, 2, 1] =
 19  21  23
 20  22  24

[:, :, 2, 2, 1] =
 25  27  29
 26  28  30

[:, :, 3, 2, 1] =
 31  33  35
 32  34  36

[:, :, 1, 1, 2] =
 1  3  5
 2  4  6

[:, :, 2, 1, 2] =
 7   9  11
 8  10  12

[:, :, 3, 1, 2] =
 13  15  17
 14  16  18

[:, :, 1, 2, 2] =
 19  21  23
 20  22  24

[:, :, 2, 2, 2] =
 25  27  29
 26  28  30

[:, :, 3, 2, 2] =
 31  33  35
 32  34  36

If the second dimension is $1$, i.e., columns are missing in each matrix, the existing column will be replicated in all the blocks. This is in keeping with the rule that everything to the left of the missing dimension is replicated.

In [89]:
b = reshape(Vector(1:(2*1*3*2*2)), 2, 1, 3, 2, 2)

2×1×3×2×2 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 1
 2

[:, :, 2, 1, 1] =
 3
 4

[:, :, 3, 1, 1] =
 5
 6

[:, :, 1, 2, 1] =
 7
 8

[:, :, 2, 2, 1] =
  9
 10

[:, :, 3, 2, 1] =
 11
 12

[:, :, 1, 1, 2] =
 13
 14

[:, :, 2, 1, 2] =
 15
 16

[:, :, 3, 1, 2] =
 17
 18

[:, :, 1, 2, 2] =
 19
 20

[:, :, 2, 2, 2] =
 21
 22

[:, :, 3, 2, 2] =
 23
 24

In [90]:
o .* b

2×3×3×2×2 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 1  1  1
 2  2  2

[:, :, 2, 1, 1] =
 3  3  3
 4  4  4

[:, :, 3, 1, 1] =
 5  5  5
 6  6  6

[:, :, 1, 2, 1] =
 7  7  7
 8  8  8

[:, :, 2, 2, 1] =
  9   9   9
 10  10  10

[:, :, 3, 2, 1] =
 11  11  11
 12  12  12

[:, :, 1, 1, 2] =
 13  13  13
 14  14  14

[:, :, 2, 1, 2] =
 15  15  15
 16  16  16

[:, :, 3, 1, 2] =
 17  17  17
 18  18  18

[:, :, 1, 2, 2] =
 19  19  19
 20  20  20

[:, :, 2, 2, 2] =
 21  21  21
 22  22  22

[:, :, 3, 2, 2] =
 23  23  23
 24  24  24

Again, just like numpy broadcasting, if any other dimension is missing, Julia cannot unsqueeze dimensions anywhere in the middle. `o` is $2 \times 3 \times 3 \times 2 \times 2$ and lets have another tensor `b_` that is $2 \times 3 \times 2 \times 2$. A new dimension can be added in the second place or the third place, but Julia does not know where. So this will fail.

In [91]:
b_ = reshape(b, 2, 3, 2, 2)

2×3×2×2 Array{Int64, 4}:
[:, :, 1, 1] =
 1  3  5
 2  4  6

[:, :, 2, 1] =
 7   9  11
 8  10  12

[:, :, 1, 2] =
 13  15  17
 14  16  18

[:, :, 2, 2] =
 19  21  23
 20  22  24

In [92]:
# This will not work
o .* b_

DimensionMismatch: DimensionMismatch: arrays could not be broadcast to a common size: a has axes Base.OneTo(3) and b has axes Base.OneTo(2)

Just like in numpy, the mismatched dimension must be exactly $1$ for broadcast to work. If I try to broadcast $2 \times 2 \times 3 \times 2 \times 2$ with $2 \times 3 \times 3 \times 2 \times 2$, it will fail

In [93]:
c = reshape(Vector(1:(2*2*3*2*2)), 2, 2, 3, 2, 2)

2×2×3×2×2 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 1  3
 2  4

[:, :, 2, 1, 1] =
 5  7
 6  8

[:, :, 3, 1, 1] =
  9  11
 10  12

[:, :, 1, 2, 1] =
 13  15
 14  16

[:, :, 2, 2, 1] =
 17  19
 18  20

[:, :, 3, 2, 1] =
 21  23
 22  24

[:, :, 1, 1, 2] =
 25  27
 26  28

[:, :, 2, 1, 2] =
 29  31
 30  32

[:, :, 3, 1, 2] =
 33  35
 34  36

[:, :, 1, 2, 2] =
 37  39
 38  40

[:, :, 2, 2, 2] =
 41  43
 42  44

[:, :, 3, 2, 2] =
 45  47
 46  48

In [94]:
# This will fail
o .* c

DimensionMismatch: DimensionMismatch: arrays could not be broadcast to a common size: a has axes Base.OneTo(3) and b has axes Base.OneTo(2)

If the first dimension is $1$, then the rule of everything to the left will be replicated does not hold. In this case the row will be replicated.

In [97]:
d = reshape(Vector(1:(1*3*3*2*2)), 1, 3, 3, 2, 2)

1×3×3×2×2 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 1  2  3

[:, :, 2, 1, 1] =
 4  5  6

[:, :, 3, 1, 1] =
 7  8  9

[:, :, 1, 2, 1] =
 10  11  12

[:, :, 2, 2, 1] =
 13  14  15

[:, :, 3, 2, 1] =
 16  17  18

[:, :, 1, 1, 2] =
 19  20  21

[:, :, 2, 1, 2] =
 22  23  24

[:, :, 3, 1, 2] =
 25  26  27

[:, :, 1, 2, 2] =
 28  29  30

[:, :, 2, 2, 2] =
 31  32  33

[:, :, 3, 2, 2] =
 34  35  36

In [98]:
o .* d

2×3×3×2×2 Array{Int64, 5}:
[:, :, 1, 1, 1] =
 1  2  3
 1  2  3

[:, :, 2, 1, 1] =
 4  5  6
 4  5  6

[:, :, 3, 1, 1] =
 7  8  9
 7  8  9

[:, :, 1, 2, 1] =
 10  11  12
 10  11  12

[:, :, 2, 2, 1] =
 13  14  15
 13  14  15

[:, :, 3, 2, 1] =
 16  17  18
 16  17  18

[:, :, 1, 1, 2] =
 19  20  21
 19  20  21

[:, :, 2, 1, 2] =
 22  23  24
 22  23  24

[:, :, 3, 1, 2] =
 25  26  27
 25  26  27

[:, :, 1, 2, 2] =
 28  29  30
 28  29  30

[:, :, 2, 2, 2] =
 31  32  33
 31  32  33

[:, :, 3, 2, 2] =
 34  35  36
 34  35  36

In [46]:
# A column vector and matrix will work with .+ but not with +
A = [
    1 2 3;
    4 5 6
]
v = [7, 8]
A .+ v

2×3 Matrix{Int64}:
  8   9  10
 12  13  14

In [47]:
# Here I am not broadcasting. The add function expects the input arrays to be of the same size.
A + v

DimensionMismatch: DimensionMismatch: a has size (2, 3), mismatch at dim 2

In [49]:
# A row vector and matrix will also work. Julia is able to figure out the right thing to do based on dimensions.
u = [7 8 9]
A .+ u

2×3 Matrix{Int64}:
  8  10  12
 11  13  15

In [50]:
A + u

DimensionMismatch: DimensionMismatch: a has size (2, 3), b has size (1, 3), mismatch at dim 1

In [51]:
# If B is a matrix with the same shape as A, then both + and .+ will work and they will give the same result
B = [
    7 8 9;
    10 11 12
]
A + B

2×3 Matrix{Int64}:
  8  10  12
 14  16  18

In [52]:
A .+ B

2×3 Matrix{Int64}:
  8  10  12
 14  16  18

In [53]:
# Matrix-Matrix multiplication will work when the dims are (m, n) and (n, p) using the * operator. 
# But .* will not work in this case.
# .* will work with (m, n) and (m, n) matrix.
C = [
    7 8;
    9 10;
    11 12
]
A * C

2×2 Matrix{Int64}:
  58   64
 139  154

In [ ]:
# This will fail
A .* C

DimensionMismatch: DimensionMismatch: arrays could not be broadcast to a common size: a has axes Base.OneTo(2) and b has axes Base.OneTo(3)

In [55]:
A .* B

2×3 Matrix{Int64}:
  7  16  27
 40  55  72

## Linear Algebra

Julia has a bunch of other [linalg operators](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/).

  * `'` will give the transpose of a real valued matrix and the Hermitian (conjugate transpose) of a complex matrix.
  * `adjoint` and `'` are equivalent.

In [56]:
A = [
    1 2 3;
    4 5 6
]
A'

3×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4
 2  5
 3  6

In [57]:
C = [
    1+0.1im 2+0.2im 3+0.3im;
    4+0.4im 5+0.5im 6+0.6im
]
C'

3×2 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
 1.0-0.1im  4.0-0.4im
 2.0-0.2im  5.0-0.5im
 3.0-0.3im  6.0-0.6im

In [58]:
adjoint(C)

3×2 adjoint(::Matrix{ComplexF64}) with eltype ComplexF64:
 1.0-0.1im  4.0-0.4im
 2.0-0.2im  5.0-0.5im
 3.0-0.3im  6.0-0.6im

In [59]:
adjoint(A)

3×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4
 2  5
 3  6