In [1]:
import numpy as np

In [13]:
A = np.arange(1, (2 * 2 * 3 * 4) + 1).reshape(4, 3, 2, 2)
A

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]],


       [[[25, 26],
         [27, 28]],

        [[29, 30],
         [31, 32]],

        [[33, 34],
         [35, 36]]],


       [[[37, 38],
         [39, 40]],

        [[41, 42],
         [43, 44]],

        [[45, 46],
         [47, 48]]]])

In [14]:
A[2]

array([[[25, 26],
        [27, 28]],

       [[29, 30],
        [31, 32]],

       [[33, 34],
        [35, 36]]])

In [16]:
A[2, 0, 0, 0]

np.int64(25)

In [17]:
np.sum(A, axis=0)

array([[[ 76,  80],
        [ 84,  88]],

       [[ 92,  96],
        [100, 104]],

       [[108, 112],
        [116, 120]]])

In [18]:
14 + 25 + 37

76

In [19]:
2 + 14 + 26 + 38

80